services:

  db:
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_PASSWORD: def12345
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes: 
  pgdata:
